const Plays = [
  { value: 1, label: "اخر رايات الاندلس" },
  { value: 2, label: "النقطة الزرقاء" },
  { value: 3, label: "هانيبال" },
  { value: 4, label: "القاع" },
  { value: 5, label: "شبح هريدي" },
  { value: 6, label: "بانجيا" },
  { value: 7, label: "2 ط نق" },
  { value: 8, label: "جرارين السواقي" },
  { value: 9, label: "شجر الدوم" },
  { value: 10, label: "لن يمروا" },
  { value: 11, label: "حذاء مثقوب تحت المطر" },
  { value: 12, label: "اخر ايام الخريف" },
  { value: 13, label: "العقد" },
  {
    value: 14,
    label: "حزينة كانت و مرعبة خضرة التل",
  },
  { value: 15, label: "تأثير جانبي" },
  { value: 16, label: "عشرة الا تلت" },
  { value: 17, label: "نهاية اللعبة" },
  { value: 18, label: "كلهم ابنائي" },
  { value: 19, label: "مرساة في محيط هستيري" },
  { value: 20, label: "ما بعد الغروب" },
  { value: 21, label: "سهرة المحروسة" },
  { value: 22, label: "انسان سعيد" },
  { value: 23, label: "علي باب الله" },
  { value: 24, label: "في ليلة واحدة" },
];

export default Plays;
